modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"
[[mods]]
modId = "uilib"
version = "${file.jarVersion}"
displayName = "UILib"
authors = "Flash"
description = '''
Flash's UI Library
'''
[[dependencies.uilib]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.uilib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
